version: '3'

services:
  sample:
    container_name: React002
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 5001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true




